### PR TITLE
feat: Provide Relay variables to render methods

### LINKED ISSUE #161: How to access route variables in Component
I'm rendering a Relay refetch container which takes fragment variables to specify a date range for which data shall be displayed. On the initial render, I want this date range to be now + some time interval, and I'm successfully using prepareVariables to inject these dynamic values. After the initial render, the user can select a date range through the UI, and a refetch can be triggered.

The problem is: I need to know the output of prepareVariables inside the rendered component. Imagine I wanted to pre-fill the date selection controls with the beginning and end dates which have dynamically been determined in prepareVariables.

How can I access those variables? It looks like they aren't exposed anywhere in match / location / etc.

Notice that those variables aren't actually route parameters - but I'm not aware of another place where I could inject the initial Relay query variables.

### PR DESCRIPTION
**Pull request by leoschweizer**
closes #161 

Pretty much all I can say about this is that this seems to work on my machine™ 😉 However I don't know nearly enough about the internals at play here to judge if there are any edge cases to be considered...

### CODE REVIEW

**Comment by taion** [comment]
This looks good to me. Can you add test coverage?

**Comment by leoschweizer** [comment]
@taion I tried, however I don't get it to work in the test case. Have a look at the updated PR, the relay variables object always is empty, although to my understanding, it shouldn't be...

**Comment by taion** [comment]
Okay, there was some ambiguity between the variables as supplied (analogous to those passed in to `<QueryRenderer>`) and the variables as used (which are only the ones the query actually uses).

I think it makes a little more sense to provide the former (i.e. to not strip out prepared variables that the query doesn't use, as those are available on Relay context anyway).

Anyway, I have things working now, but keeping things clean required changing some internal APIs, so I'm going to rebase onto `next` and cut this as an alpha.

**Comment by taion** [comment]
Released in v0.4.0-alpha.2.

**Pull request merged**
